####### ping google for check connection #######
POST http://localhost:3000/status/offline  
Content-Type: application/json
{
  "path": "http://10.240.67.14:80/api/owner/menus",
  "method": "POST",
  "statusCode": 404,
  "payload": {
    "menu_name": "thai tea ma leaew jaaa",
    "description": "thai tea from memeeeeeeeeeeeeeeeeee",
    "price": 100,
    "image_url": "http://example.com/spaghetti.jpg"
  },
  "headers": {
    "owner_id": "c630720f-f05d-4d91-ba66-8a7dd60c2353",
    "branch_id": "85f246e6-42da-4b82-8cf4-bdf2c62fa131"
  }
  }

GET http://localhost:3000/status/retry
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: 85f246e6-42da-4b82-8cf4-bdf2c62fa131






















