####### ping google for check connection #######
POST http://localhost:3000/status/offline  
Content-Type: application/json
{
  "path": "http://192.168.3.86:3000/owner/menus",
  "method": "POST",
  "statusCode": 404,
  "payload": {
    "menu_name": "ชานมมม",
    "description": "thai tea from อร่อยยยยยยยย",
    "price": 100,
    "image_url": "http://example.com/spaghetti.jpg"
  },
  "headers": {
    "owner_id": "ba9f18e5-2d91-48b9-b7c6-bb6ff70440b0",
    "branch_id": "a6f7afc2-7908-405a-a348-1f9ed115a35f"
  }}

GET http://localhost:3000/status/retry
Content-Type: application/json
owner_id: ba9f18e5-2d91-48b9-b7c6-bb6ff70440b0
branch_id:a6f7afc2-7908-405a-a348-1f9ed115a35f






















