### 1. Owner สมัครใช้งาน (Register)
POST http://localhost:3000/owner/register
Content-Type: application/json

{
  "owner_name": "Owner",
  "contact_info": "0123456789",
  "email": "ownername1@gmail.com",
  "password": "SecurePass123!"
}
### 2. Owner ใช้รหัสผ่านแบบใช้แล้วทิ้งเข้าสู่ระบบ
POST http://localhost:3000/owner/login
Content-Type: application/json

{
  "email": "ownername1@gmail.com",
  "password": "5vuixfuq"
}

### 3. Owner ขอ OTP สำหรับรีเซ็ตรหัสผ่าน (Forgot Password)
POST http://localhost:3000/owner/forgot-password
Content-Type: application/json
owner_id: 20
branch_id: 3
{
  "usernameOrEmail": "ownername1@gmail.com"
}

### 4. Owner ยืนยัน OTP
POST http://localhost:3000/owner/verify-otp
Content-Type: application/json
owner_id: 16
branch_id: 2
{
  "usernameOrEmail": "owner1@gmail.com",
  "otp": "155693"
}


### 5. Owner รีเซ็ตรหัสผ่านใหม่
PATCH http://localhost:3000/owner/reset-password
Content-Type: application/json
owner_id: 16
branch_id: 2
{
  "email": "owner1@gmail.com",
  "newPassword": "SecurePass4567!"
}

### 6. Owner สร้าง Employee (ต้องแนบ Token)
POST http://localhost:3000/owner/create-employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6MjAsImVtYWlsIjoib3duZXJuYW1lMUBnbWFpbC5jb20iLCJicmFuY2hfaWQiOjMsInJvbGVzIjpbIm93bmVyIl0sImlhdCI6MTc0MDI4MzQzOSwiZXhwIjoxNzQwMzY5ODM5fQ.Xh3axKrHgONip-VNU_qnttnzEI1UQU583SUz3UOmRsI
Content-Type: application/json
owner_id: 20
branch_id: 3
{
  "email": "employeememeebranchone1@example.com",
  "password": "EmployeePass123!"
}

### Owner อัปโหลดไฟล์ CSV
POST http://localhost:3000/owner/upload-csv
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="owners.csv"
Content-Type: text/csv

< /Users/watcharapolyotadee/Development/POS/POS-backend-nest/src/uploads/owners.csv
--boundary--


GET http://localhost:3000/owner/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6MjAsImVtYWlsIjoib3duZXJuYW1lMUBnbWFpbC5jb20iLCJicmFuY2hfaWQiOjMsInJvbGVzIjpbIm93bmVyIl0sImlhdCI6MTc0MDI4MzQzOSwiZXhwIjoxNzQwMzY5ODM5fQ.Xh3axKrHgONip-VNU_qnttnzEI1UQU583SUz3UOmRsI


###  Owner ตรวจสอบว่ามี Employee อย่างน้อย 1 คน
GET http://localhost:3000/owner/check-employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6MjAsImVtYWlsIjoib3duZXJuYW1lMUBnbWFpbC5jb20iLCJicmFuY2hfaWQiOjMsInJvbGVzIjpbIm93bmVyIl0sImlhdCI6MTc0MDI4MzQzOSwiZXhwIjoxNzQwMzY5ODM5fQ.Xh3axKrHgONip-VNU_qnttnzEI1UQU583SUz3UOmRsI

###  Owner ดูข้อมูลตัวเอง
GET http://localhost:3000/owner/profile
Authorization: Bearer {{TOKEN}}


### Dev only สร้าง employee ใหม่
POST http://localhost:3000/owner/create-employee-dev
Content-Type: application/json

{
  "email": "employee@gmail.com",
  "password": "EmployeePass123!",
  "manager_id": 2
}