### Register New Owner
POST http://localhost:3000/owner/register
Content-Type: application/json
{
  "owner_name": "Owner FluekFix",
  "contact_info": "0840969769",
  "email": "ownerFluk@gmail.com",
  "password": "OwnerTest",
  "role": "owner"
}

### Create Employee
POST http://localhost:3000/owner/create-employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6NSwiZW1haWwiOiJhZG1pbkZsdWtAZ21haWwuY29tIiwiYnJhbmNoX2lkIjpudWxsLCJyb2xlcyI6WyJvd25lciJdLCJpYXQiOjE3Mzk4ODY3NDksImV4cCI6MTczOTk3MzE0OX0.B0PWsLgofCubNILo-gzP3Fk8TY-wakR82lLeC82xHtE
Content-Type: application/json

{
  "email": "employee2@example.com",
  "password": "employee1234",
  "owner_id": 1
}

### Count Employees
GET http://localhost:3000/owner/count-employees?owner_id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6NSwiZW1haWwiOiJhZG1pbkZsdWtAZ21haWwuY29tIiwiYnJhbmNoX2lkIjpudWxsLCJyb2xlcyI6WyJvd25lciJdLCJpYXQiOjE3Mzk4ODY3NDksImV4cCI6MTczOTk3MzE0OX0.B0PWsLgofCubNILo-gzP3Fk8TY-wakR82lLeC82xHtE



### Login Owner
POST http://localhost:3000/owner/login
Content-Type: application/json
{
  "email": "adminFluk@gmail.com",
  "password": "AdminTestNew"
}

### Get Profile
GET http://localhost:3000/owner/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6NSwiZW1haWwiOiJhZG1pbkZsdWtAZ21haWwuY29tIiwiYnJhbmNoX2lkIjpudWxsLCJyb2xlcyI6WyJvd25lciJdLCJpYXQiOjE3Mzk4OTAxMDUsImV4cCI6MTczOTk3NjUwNX0.O5MsndiRjiuLLsqwtAq5duU6TzlwMIOiiLcjvIsXRas

### Owner Dashboard
GET http://localhost:3000/owner/dashboard
Authorization: Bearer Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6NSwiZW1haWwiOiJhZG1pbkZsdWtAZ21haWwuY29tIiwiYnJhbmNoX2lkIjpudWxsLCJyb2xlcyI6WyJvd25lciJdLCJpYXQiOjE3Mzk4ODY3NDksImV4cCI6MTczOTk3MzE0OX0.B0PWsLgofCubNILo-gzP3Fk8TY-wakR82lLeC82xHtE


### Employee Dashboard
GET http://localhost:3000/employee/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6NSwiZW1haWwiOiJhZG1pbkZsdWtAZ21haWwuY29tIiwiYnJhbmNoX2lkIjpudWxsLCJyb2xlcyI6WyJvd25lciJdLCJpYXQiOjE3Mzg4NzA5MjQsImV4cCI6MTczODk1NzMyNH0.buRyJBmbNH_3H28lb5YwU8kdy-5J6FH34fshlK-5_tM

### Admin Dashboard
GET http://localhost:3000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6NSwiZW1haWwiOiJhZG1pbkZsdWtAZ21haWwuY29tIiwiYnJhbmNoX2lkIjpudWxsLCJyb2xlcyI6WyJvd25lciJdLCJpYXQiOjE3Mzg4NzA5MjQsImV4cCI6MTczODk1NzMyNH0.buRyJBmbNH_3H28lb5YwU8kdy-5J6FH34fshlK-5_tM


### Upload CSV with Owner Data
POST http://localhost:3000/owner/upload-csv
Content-Type: multipart/form-data
file=@./uploads/owners.csv

### Send OTP
POST http://localhost:3000/owner/forgot-password
Content-Type: application/json
{
  "usernameOrEmail": "adminFluk@gmail.com"
}
### Verify OTP
POST http://localhost:3000/owner/verify-otp
Content-Type: application/json
{
  "usernameOrEmail": "adminFluk@gmail.com",
  "otp": "790362"
}

### Reset Password
PATCH http://localhost:3000/owner/reset-password/5
Content-Type: application/json
{
  "newPassword": "AdminTestNew"
}

GET http://localhost:3000/owner/ingredients/16