
GET http://localhost:3000/owner/ingredient/4


GET http://localhost:3000/owner/ingredient/menu/1

### หาวัตถุดิบที่ผูกทั้งหมด👌
GET http://localhost:3000/owner/ingredient
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

