### Create a new Menu
POST http://localhost:3000/owner/menus
Content-Type: application/json
owner_id: 1
branch_id: 1
{
  "menu_name": "ชานมถั่วเหลือง",
  "description": "Delicious ชานมถั่วเหลือง",
  "price": 30,
  "image_url": "http://example.com/spaghetti.jpg"
}

### Get all Menus
GET http://localhost:3000/owner/menus
Content-Type: application/json
owner_id: 1
branch_id: 1

### Get a specific Menu by ID
GET http://localhost:3000/owner/menus/1

### Update a Menu by ID
PATCH http://localhost:3000/owner/menus/1
Content-Type: application/json
{
  "menu_name": "latte milk",
  "price": 14.99,
  "description": "coffee with milk"
}

### Delete a Menu by ID
DELETE http://localhost:3000/owner/menus/1
owner_id: 1
branch_id: 1


### link menu for auto cut stock
PATCH http://localhost:3000/owner/menus/stock/16
Content-Type: application/json
{
  "owner_id": 2,
  "branch_id": 2,
  "menuData": [
    {
      "ingredient_name": "น้ำเชื่อม",
      "unit": "ml",
      "ingredientListForStock": [
        { "size_id": 1, "menu_type_id": 1, "quantity_used": 10 },
        { "size_id": 1, "menu_type_id": 2, "quantity_used": 20 },
        { "size_id": 1, "menu_type_id": 3, "quantity_used": 30 },
        { "size_id": 2, "menu_type_id": 1, "quantity_used": 5 },
        { "size_id": 2, "menu_type_id": 2, "quantity_used": 10 },
        { "size_id": 2, "menu_type_id": 3, "quantity_used": 20 },
        { "size_id": 3, "menu_type_id": 1, "quantity_used": 12 },
        { "size_id": 3, "menu_type_id": 2, "quantity_used": 22 },
        { "size_id": 3, "menu_type_id": 3, "quantity_used": 35 }
      ]
    },
    {
      "ingredient_name": "น้ำส้ม",
      "unit": "ml",
      "ingredientListForStock": [
        { "size_id": 1, "menu_type_id": 1, "quantity_used": 10 },
        { "size_id": 1, "menu_type_id": 2, "quantity_used": 20 },
        { "size_id": 1, "menu_type_id": 3, "quantity_used": 30 },
        { "size_id": 2, "menu_type_id": 1, "quantity_used": 7 },
        { "size_id": 2, "menu_type_id": 2, "quantity_used": 10 },
        { "size_id": 2, "menu_type_id": 3, "quantity_used": 20 },
        { "size_id": 3, "menu_type_id": 1, "quantity_used": 12 },
        { "size_id": 3, "menu_type_id": 2, "quantity_used": 22 },
        { "size_id": 3, "menu_type_id": 3, "quantity_used": 37 }
      ]
    }
  ]
}
