### สร้าง sweetness ผูกกับ menu 👌
POST http://localhost:3000/owner/menus/options/sweetness
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "sweetness_group_name": "ความหวานนม",
  "options": [
    "หวานน้อย",
    "หวานกลาง",
    "หวานมาก"
  ],
  "menu_id": ["4158398f-a29e-42ed-a085-f168446527fc","33769a3a-5bfb-41c8-8971-744dae1d92aa"]
}

### แก้ไข sweetness ผูกกับ menu 👌
PATCH http://localhost:3000/owner/menus/options/sweetness
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "old_sweetness_group_name": "ความหวานนม",
  "new_sweetness_group_name": "ความหวานนม",
  "options": [
    { "sweetness_id": "66baeb58-aca4-4e34-ac17-ab4887f17be6", "level_name": "หวานน้อยๆ" },
    { "sweetness_id": "ddd9e5ba-67c7-4a24-8052-e6c34d140f71", "level_name": "หวานกลางๆ" },
    { "sweetness_id": "260bde44-5398-47b1-9459-bc153f79546a", "level_name": "หวานมากๆ" },
    { "sweetness_id": null,"level_name": "หวานมากๆqqq"}
  ],
  "menu_id": ["faa9a7c2-a956-4153-a4d2-eb436a90c2a2","4158398f-a29e-42ed-a085-f168446527fc","33769a3a-5bfb-41c8-8971-744dae1d92aa"]
}

### ลบ sweetness ผูกกับ menu 👌
DELETE http://localhost:3000/owner/menus/options/sweetness/ความหวานนม
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

###ดูรายละเอียด menu จาก menu_id👌
GET http://localhost:3000/owner/menus/33769a3a-5bfb-41c8-8971-744dae1d92aa

PATCH http://localhost:3000/owner/menus/options/sweetness/104
Content-Type: application/json
{
  "name": "น้อยมากแต่หวาน",
  "menu_id": [15, 16, 10],
  "is_required":true
}

###เพิ่ม Addon ผูกกับ menu👌
POST http://localhost:3000/owner/menus/options/add-ons
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

{
  "options": [
    { "บุก2": { "price": "10.00", "unit": "กรัม", "quantity":12 } },
    { "ไข่มุก2": { "price": "20.00", "unit": "กรัม", "quantity":15 } }
  ],
  "menu_id": ["4158398f-a29e-42ed-a085-f168446527fc","33769a3a-5bfb-41c8-8971-744dae1d92aa"],
  "is_required":true,
  "is_multipled":true
}

# edit add on option👌
PATCH http://localhost:3000/owner/menus/options/add-ons
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "options": [
    { 
      "add_on_id": "89c7a2de-9a35-42d4-b652-c74ce83a23ad",
      "add_on_name": "บุก",
      "price": "10.00",
      "quantity": 20,
      "unit": "กรัม"
    },
    { 
      "add_on_id": "884eb457-fd01-410c-8010-cb7900760baf",
      "add_on_name": "ไข่มุก",
      "price": "25.00",
      "quantity": 12,
      "unit": "g"
    }
  ],
  "menu_id": ["937a85a7-168c-4bc3-91c4-a5d0a66f6ef2","bb24ae81-b635-49df-a74b-5b9cac4e4633","faa9a7c2-a956-4153-a4d2-eb436a90c2a2"],
  "is_require": false,
  "is_multiple": true
}

### เพิ่ม size ผูกกับ menu👌
POST http://localhost:3000/owner/menus/options/size
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

{
  "size_group_name": "ขนาดแก้วสำหรับนม",
   "options": [
    { "s":  { "price": "5.00" } },
    { "m":  { "price": "10.00" } },
    { "l":  { "price": "15.00" } }
  ],
  "menu_id": ["4158398f-a29e-42ed-a085-f168446527fc","33769a3a-5bfb-41c8-8971-744dae1d92aa"]
}

# edit size option👌
PATCH http://localhost:3000/owner/menus/options/size
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

{
  "old_size_group_name": "ขนาดแก้วสำหรับนม",
  "new_size_group_name": "ขนาดแก้วสำหรับนม",
   "options": [
    { "size_id": "eb749792-4e21-4190-a632-68a4562e2aa9", "size_name":"m",  "price": "25.00" },
    { "size_id": "ddf33ee7-922e-427b-9f0a-ea218c92706b", "size_name":"l",  "price": "35.00" },
    { "size_id": "5e8cae6d-e352-4ab7-8536-1ba468b709dc", "size_name":"xl",  "price": "45.00" },
    { "size_id": null, "size_name":"xs",  "price": "45.00" }
  ],
  "menu_id": ["33769a3a-5bfb-41c8-8971-744dae1d92aa"]
}

# delete size group👌
DELETE http://localhost:3000/owner/menus/options/size/ขนาดแก้วสำหรับนม
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

### เพิ่มประเภท ร้อนเย็นปั่น ผูกกับmenu👌
POST http://localhost:3000/owner/menus/options/menu_type
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "menu_type_group_name": "สำหรับนม",
  "options": [
    { "ปั่นเย็น": "10.00" },
    { "iceน้อย": "0.00" }
  ],
  "menu_id": ["4158398f-a29e-42ed-a085-f168446527fc", "33769a3a-5bfb-41c8-8971-744dae1d92aa"]
}

### แก้ไขประเภท ร้อนเย็นปั่น ผูกกับmenu👌
PATCH http://localhost:3000/owner/menus/options/menu_type
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "old_menu_type_group_name": "สำหรับนม",
  "new_menu_type_group_name": "สำหรับนมใหม่",
  "options": [
    { "menu_type_id": "7061ae01-16bb-4e44-a593-8fa689218edf", "type_name": "เย็น", "price_difference": 5.00 },
    { "menu_type_id": "7b8e5fdc-0f58-427c-a14e-a07db31c5ab8", "type_name": "ปั่น", "price_difference": 10.00 },
    { "menu_type_id": null, "type_name": "ร้อน", "price_difference": 0.00 }
  ],
  "menu_id": ["4158398f-a29e-42ed-a085-f168446527fc", "33769a3a-5bfb-41c8-8971-744dae1d92aa","faa9a7c2-a956-4153-a4d2-eb436a90c2a2"]
}

### ลบประเภท ร้อนเย็นปั่น ผูกกับmenu👌
DELETE http://localhost:3000/owner/menus/options/menu_type/สำหรับนมใหม่
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

# GET http://localhost:3000/owner/menus/14

# GET http://localhost:3000/owner/menus/options/add-ons

# GET http://localhost:3000/owner/menus/options/size

# GET http://localhost:3000/owner/menus/options/sweetness

# GET http://localhost:3000/owner/menus/options/menu-type

# Delete all add-ons
DELETE http://localhost:3000/owner/menus/options/add-ons
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

### Get sweetness group data
GET http://localhost:3000/owner/menus/options/sweetness/ระดับความหวานทั่วไป
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

### Get size group data👌
GET http://localhost:3000/owner/menus/options/size/ขนาดแก้วสำหรับนม
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

### Get menu type group data👌
GET http://localhost:3000/owner/menus/options/menu-type/สำหรับนมใหม่
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

### Get add-on group data
GET http://localhost:3000/owner/menus/options/add-on
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

### Get all option groups
GET http://localhost:3000/owner/menus/options/groups
Content-Type: application/json
owner_id: 6
branch_id: 3

### Get menu options by menu id for cut stock
GET http://localhost:3000/owner/menus/stock/option/7
Content-Type: application/json
owner_id: 6
branch_id: 3
