### Create a new Branch
POST http://localhost:3000/branches
Content-Type: application/json

{
  "branch_name": "MeMeem Branch",
  "branch_address": "123 Main Street",
  "branch_phone_number": "123456789",
  "owner_id": 6
}

### Get all Branches
GET http://localhost:3000/branches

### Get all Branches by owner_id
GET http://localhost:3000/branches/owner/c630720f-f05d-4d91-ba66-8a7dd60c2353
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353

### Get a specific Branch by ID
GET http://localhost:3000/branches/3

### Update a Branch by ID
PATCH http://localhost:3000/branches/5
Content-Type: application/json

{
  "branch_name": "Updated Branch Name",
  "branch_address": "456 Secondary Street"
}

### Delete a Branch by ID
DELETE http://localhost:3000/branches/4

### Get Owner's Branches (อื่นๆที่ไม่ใช่ตัวเอง)
GET http://localhost:3000/branches/owner/my-branches
Content-Type: application/json
owner_id: 1
branch_id: 1

### Get Branch Setup
GET http://192.168.1.53:3000/branches/owner/get-branch-setup/d458dffa-855b-4040-afba-dbf97055a820
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353

### Clone Branch Setup /branch ที่ต้องการจะ clone
POST http://localhost:3000/branches/owner/clone-branch-setup/d458dffa-855b-4040-afba-dbf97055a820
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: 25b217e3-6158-4edb-98e2-5fad824f8d92