### Get Stock Summary by Date
GET http://localhost:3000/owner/stock-summary/2025-01-01
GET http://localhost:3000/owner/stock-ingredients/2

GET http://localhost:3000/owner/stock-orders/2025-01-01

GET http://localhost:3000/owner/stock-cancel-orders

GET http://localhost:3000/owner/orders/32


POST http://localhost:3000/owner/stock-group
Content-Type: application/json
{
    "category_name": "Topping"
}

POST http://localhost:3000/owner/create-stock-ingredients
Content-Type: application/json
{
  "ingredient_id": 2,
  "ingredient_name": "วุ้นมะพร้าว",
  "net_volume": 250,
  "quantity_in_stock": 3,
  "total_volume": 100,
  "category_name": "ท็อปปิ้ง",
  "expiration_date": "2025-01-24"
}
PATCH http://localhost:3000/owner/orders/2
Content-Type: application/json

{
  "cancel_status": "คืนเงินเสร็จสิ้น"
}

