### Get Stock Summary by Date
GET http://localhost:3000/owner/stock-summary/2025-01-01
GET http://localhost:3000/owner/stock-ingredients/2

GET http://localhost:3000/owner/stock-orders/2025-01-01

GET http://localhost:3000/owner/stock-cancel-orders

GET http://localhost:3000/owner/orders/32

GET http://localhost:3000/owner/stock-ingredients

# getIngredientsCategories
GET http://localhost:3000/owner/stock-ingredients/categories

# getIngredientDetails
GET http://localhost:3000/owner/stock-ingredients/18

#getUpdateIngredient
GET http://localhost:3000/owner/update-stock-ingredients/18


POST http://localhost:3000/owner/stock-group
Content-Type: application/json
{
    "category_name": "เครื่องครัว"
}

POST http://localhost:3000/owner/create-stock-ingredients
Content-Type: application/json
{
  "image_url": "imagepath/image.png",
  "ingredient_name": "ผงโกโก้ทิวลิป",
  "net_volume": 250,
  "unit": "g",
  "quantity_in_stock": 1,
  "category_name": "วัตถุดิบ",
  "expiration_date": "2025-01-27",
  "owner_id": 1
}
PATCH http://localhost:3000/owner/orders/32
Content-Type: application/json

{
  "cancel_status": "คืนเงินเสร็จสิ้น"
  // "cancel_status": "ยังไม่คืนเงิน"
}

