### Get Stock Summary by Date
GET http://localhost:3000/owner/stock-summary/2025-03-17
Content-Type: application/json
owner_id: 1
branch_id: 3

GET http://localhost:3000/owner/stock-sale/2025/03
Content-Type: application/json
owner_id: 1
branch_id: 3

## GET ALL ORDERS
GET http://localhost:3000/owner/stock-orders/2025-03-07/year
Content-Type: application/json
owner_id: 1
branch_id: 3

## get menu ingredient by ingredient id👌
GET http://localhost:3000/owner/stock-ingredients/2d20c47c-2be2-42a0-8530-fe7bab222fe4
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

## GET ALL CANCEL ORDERS
GET http://localhost:3000/owner/stock-cancel-orders
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

## update cancel order status
PATCH http://localhost:3000/owner/orders/71
Content-Type: application/json
owner_id: 1
branch_id: 1
{
  "cancel_status": "คืนเงินเสร็จสิ้น"
}

## get menu detail by order_id
GET http://localhost:3000/owner/orders/68
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

## GET ALL INGREDIENT👌
GET http://localhost:3000/owner/stock-ingredients
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

### GET sub ingredient by ingredient_id
GET http://localhost:3000/owner/stock-ingredients/sub-ingredient/2d20c47c-2be2-42a0-8530-fe7bab222fe4
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

# getIngredientsCategories
GET http://localhost:3000/owner/stock-ingredients/categories
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

# getIngredientDetails by ingredient_id👌
GET http://localhost:3000/owner/stock-ingredients/2d20c47c-2be2-42a0-8530-fe7bab222fe4
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

#getUpdateIngredient by update_id
## fix
GET http://localhost:3000/owner/update-stock-ingredients/15
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

## update ingredient popup
PATCH http://localhost:3000/owner/update-stock-ingredients/15
Content-Type: application/json
owner_id: 1
branch_id: 1
branch_id: 1
{
  "quantity_in_stock": 100,
  "total_volume": 10000,
  "net_volume": 100,
  "expiration_date": "2026-02-28"
}

### Create Ingredient Category👌
POST http://localhost:3000/owner/stock-group
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
    "category_name": "น้ำหวาน"
}

## create new ingredient update👌
POST http://localhost:3000/owner/create-stock-ingredients
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "image_url": "imagepath/image.png",
  "ingredient_name": "ไข่มุก2",
  "net_volume": 1000,
  "unit": "g",
  "quantity_in_stock": 4,
  "category_name": "น้ำหวาน",
  "expiration_date": "2025-05-29"
}

## DELETE Ingredient👌
PATCH http://localhost:3000/owner/stock-ingredients/1dfef6a6-e7c8-4149-b1e6-f35526286cb0
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820


### edit ingredient detail by ingredient_id👌
PATCH http://localhost:3000/owner/edit-stock-ingredients/1dfef6a6-e7c8-4149-b1e6-f35526286cb0
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "image_url": "https://www.starbucks.co.th/stb-media/2020/08/81.Iced-Green-Tea-Latte1080.png",
  "ingredient_name" : "ไข่มุก3",
  "unit": "g",
  "category_name": "ท็อปปิ้ง"
}
