GET http://10.66.14.48:3000/sync/check-connection
Content-Type: application/json
owner_id: 1
branch_id: 1

### Get sync status for a branch
GET http://10.66.14.48:3000/sync/status
Content-Type: application/json
owner_id: 1
branch_id: 1

### Manually trigger data sync
POST http://10.66.14.48.80:3000/sync/sync-now
Content-Type: application/json
owner_id: 1
branch_id: 1

GET http://10.66.14.48:3000/sync/test/internet-check



POST http://10.66.14.48:3000/sync-status/test-sync
Content-Type: application/json
{
  "path": "https://api.example.com/data",
  "statusCode": 404,
  "data": {
    "key": "value"
  }
}


GET http://10.66.14.48:3000/sync-status/pending-syncs


DELETE http://10.66.14.48:3000/sync-status/clear-syncs