### Create a new Category

### Get a specific Category by ID
GET http://localhost:3000/owner/categories

### Get a specific Category by ID
GET http://localhost:3000/owner/categories/15

### Delete a Category by ID
DELETE http://localhost:3000/owner/categories/14
Content-Type: application/json
owner_id: 1
branch_id: 1

# POST http://localhost:3000/owner/categories/link-menus
# Content-Type: application/json

# {
#   "category_id": 5,
#   "menu_ids": [6,7]
# }

GET http://localhost:3000/owner/categories/5/menus
Content-Type: application/json
owner_id: 1
branch_id: 1


POST http://localhost:3000/owner/categories
Content-Type: application/json
owner_id: 1
branch_id: 1
{
  "category_name": "ชา",
  "menu_id": [1,2]
}


PATCH http://localhost:3000/owner/categories/13
Content-Type: application/json
owner_id: 1
branch_id: 1
{
  "category_name": "promotion",
  "menu_id": [1,2,3]
}

### Link menu to category
POST http://localhost:3000/owner/categories/link-menus
Content-Type: application/json
owner_id: 1
branch_id: 1
{
  "category_id": 1,
  "menu_ids": [1,2,3]
}
