### Create a new Category

### Get a specific Category by ID 👌
GET http://localhost:3000/owner/categories
owner_id: 1
branch_id: 3

### Get a specific Category by ID 👌
GET http://localhost:3000/owner/categories/05754dbe-c05d-4240-af6c-52dbf5dbe459

### Delete a Category by ID 👌
DELETE http://localhost:3000/owner/categories/459b8405-702f-48cd-845b-592bd2b35413
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820

### getMenusByCategory 👌
GET http://localhost:3000/owner/categories/05754dbe-c05d-4240-af6c-52dbf5dbe459/menus
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820


###ผูก menu กับ category 👌
POST http://localhost:3000/owner/categories
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "category_name": "ยอดฮิต",
  "menu_id": ["937a85a7-168c-4bc3-91c4-a5d0a66f6ef2","faa9a7c2-a956-4153-a4d2-eb436a90c2a2","d3f37e87-c67f-4e8c-8a0d-f2442fa9e4da","33769a3a-5bfb-41c8-8971-744dae1d92aa"]
}

#แก้ไข การผูก menu กับ category 👌
PATCH http://localhost:3000/owner/categories/cdc5b074-2a8f-4fc6-9b8a-93e1e4590c77
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
{
  "category_name": "ชานมอร่อยมากๆ",
  "menu_id": ["bb24ae81-b635-49df-a74b-5b9cac4e4633","937a85a7-168c-4bc3-91c4-a5d0a66f6ef2"]
}


### Get all categories with their menus 👌
GET http://localhost:3000/owner/categories/all/menus
Content-Type: application/json
owner_id: c630720f-f05d-4d91-ba66-8a7dd60c2353
branch_id: d458dffa-855b-4040-afba-dbf97055a820
