### 1. Owner อัปโหลดไฟล์ CSV
POST http://localhost:3000/owner/upload-csv
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="owners.csv"
Content-Type: text/csv

< /Users/watcharapolyotadee/Development/POS/POS-backend-nest/src/uploads/owners.csv
--boundary--

### 2. Owner เข้าสู่ระบบ (Login)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "charlie.white@example.com",
  "password": "g888bswf"
}

### 3. Owner ขอ OTP สำหรับรีเซ็ตรหัสผ่าน (Forgot Password)
POST http://localhost:3000/owner/forgot-password
Content-Type: application/json
owner_id: 6
branch_id: 6
{
  "usernameOrEmail": "charlie.white@example.com"
}
### 4. Owner ยืนยัน OTP
POST http://localhost:3000/owner/verify-otp
Content-Type: application/json
owner_id: 6
branch_id: 6
{
  "usernameOrEmail": "charlie.white@example.com",
  "otp": "888977"
}

### 5. Owner รีเซ็ตรหัสผ่านใหม่
PATCH http://localhost:3000/owner/reset-password
Content-Type: application/json
owner_id: 6
branch_id: 6
{
  "email": "charlie.white@example.com",
  "newPassword": "SecureWhite123!"
}
### 6. Owner เข้าสู่ระบบ (Login)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "charlie.white@example.com",
  "password": "SecureWhite123!"
}
### 7. Owner สร้าง Employee (ต้องแนบ Token)
POST http://localhost:3000/owner/create-employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcl9pZCI6NiwiZW1haWwiOiJjaGFybGllLndoaXRlQGV4YW1wbGUuY29tIiwiYnJhbmNoX2lkIjo2LCJyb2xlcyI6WyJvd25lciJdLCJpYXQiOjE3NDA1OTQyMzcsImV4cCI6MTc0MDY4MDYzN30.Ug1donayg6_dhz0aCtMftFtY6YiAyAT5ma0oni80UrI
Content-Type: application/json

{
  "email": "MemeeEmployee2@example.com",
  "password": "Employee2",
  "branch_id": 6
}
